CREATE DATABASE IF NOT EXISTS `kotlin_project`;

USE `kotlin_project`;

CREATE TABLE IF NOT EXISTS users (
  `ID` INT PRIMARY KEY,
	`EXTRA_DATA` VARCHAR(200) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;